# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf6ac88054095bcb042ec7f8b576e00aae5241a56a700218054e791e9579147f2ed0ac87f4dfa7b9f5419b95c94d8abce3811c7471030dc2402cbd26199c2ba8

test:
  secret_key_base: 3c9745c996c51ab708b7eb01509d63ebd772defb13a9c5a2f85bc29b7654c2e1a92ed141d774ae996e1aec48713fea7796ea81c48cc91d15bd1ee757d9059843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
